/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExercicesIndexRouteImport } from './routes/exercices.index'
import { Route as ExamensIndexRouteImport } from './routes/examens.index'
import { Route as DemonstrationsIndexRouteImport } from './routes/demonstrations.index'
import { Route as DemonstrationsDemoIdRouteImport } from './routes/demonstrations.$demoId'
import { Route as CoursChapterIdRouteImport } from './routes/cours.$chapterId'
import { Route as ExercicesChapterIdIndexRouteImport } from './routes/exercices.$chapterId.index'
import { Route as ExamensExamIdIndexRouteImport } from './routes/examens.$examId.index'
import { Route as ExercicesChapterIdExerciseIdRouteImport } from './routes/exercices.$chapterId.$exerciseId'
import { Route as ExamensExamIdQuestionIdRouteImport } from './routes/examens.$examId.$questionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesIndexRoute = ExercicesIndexRouteImport.update({
  id: '/exercices/',
  path: '/exercices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamensIndexRoute = ExamensIndexRouteImport.update({
  id: '/examens/',
  path: '/examens/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstrationsIndexRoute = DemonstrationsIndexRouteImport.update({
  id: '/demonstrations/',
  path: '/demonstrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstrationsDemoIdRoute = DemonstrationsDemoIdRouteImport.update({
  id: '/demonstrations/$demoId',
  path: '/demonstrations/$demoId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursChapterIdRoute = CoursChapterIdRouteImport.update({
  id: '/cours/$chapterId',
  path: '/cours/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesChapterIdIndexRoute = ExercicesChapterIdIndexRouteImport.update({
  id: '/exercices/$chapterId/',
  path: '/exercices/$chapterId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamensExamIdIndexRoute = ExamensExamIdIndexRouteImport.update({
  id: '/examens/$examId/',
  path: '/examens/$examId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesChapterIdExerciseIdRoute =
  ExercicesChapterIdExerciseIdRouteImport.update({
    id: '/exercices/$chapterId/$exerciseId',
    path: '/exercices/$chapterId/$exerciseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamensExamIdQuestionIdRoute = ExamensExamIdQuestionIdRouteImport.update({
  id: '/examens/$examId/$questionId',
  path: '/examens/$examId/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cours/$chapterId': typeof CoursChapterIdRoute
  '/demonstrations/$demoId': typeof DemonstrationsDemoIdRoute
  '/demonstrations/': typeof DemonstrationsIndexRoute
  '/examens/': typeof ExamensIndexRoute
  '/exercices/': typeof ExercicesIndexRoute
  '/examens/$examId/$questionId': typeof ExamensExamIdQuestionIdRoute
  '/exercices/$chapterId/$exerciseId': typeof ExercicesChapterIdExerciseIdRoute
  '/examens/$examId/': typeof ExamensExamIdIndexRoute
  '/exercices/$chapterId/': typeof ExercicesChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cours/$chapterId': typeof CoursChapterIdRoute
  '/demonstrations/$demoId': typeof DemonstrationsDemoIdRoute
  '/demonstrations': typeof DemonstrationsIndexRoute
  '/examens': typeof ExamensIndexRoute
  '/exercices': typeof ExercicesIndexRoute
  '/examens/$examId/$questionId': typeof ExamensExamIdQuestionIdRoute
  '/exercices/$chapterId/$exerciseId': typeof ExercicesChapterIdExerciseIdRoute
  '/examens/$examId': typeof ExamensExamIdIndexRoute
  '/exercices/$chapterId': typeof ExercicesChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cours/$chapterId': typeof CoursChapterIdRoute
  '/demonstrations/$demoId': typeof DemonstrationsDemoIdRoute
  '/demonstrations/': typeof DemonstrationsIndexRoute
  '/examens/': typeof ExamensIndexRoute
  '/exercices/': typeof ExercicesIndexRoute
  '/examens/$examId/$questionId': typeof ExamensExamIdQuestionIdRoute
  '/exercices/$chapterId/$exerciseId': typeof ExercicesChapterIdExerciseIdRoute
  '/examens/$examId/': typeof ExamensExamIdIndexRoute
  '/exercices/$chapterId/': typeof ExercicesChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cours/$chapterId'
    | '/demonstrations/$demoId'
    | '/demonstrations/'
    | '/examens/'
    | '/exercices/'
    | '/examens/$examId/$questionId'
    | '/exercices/$chapterId/$exerciseId'
    | '/examens/$examId/'
    | '/exercices/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cours/$chapterId'
    | '/demonstrations/$demoId'
    | '/demonstrations'
    | '/examens'
    | '/exercices'
    | '/examens/$examId/$questionId'
    | '/exercices/$chapterId/$exerciseId'
    | '/examens/$examId'
    | '/exercices/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/cours/$chapterId'
    | '/demonstrations/$demoId'
    | '/demonstrations/'
    | '/examens/'
    | '/exercices/'
    | '/examens/$examId/$questionId'
    | '/exercices/$chapterId/$exerciseId'
    | '/examens/$examId/'
    | '/exercices/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursChapterIdRoute: typeof CoursChapterIdRoute
  DemonstrationsDemoIdRoute: typeof DemonstrationsDemoIdRoute
  DemonstrationsIndexRoute: typeof DemonstrationsIndexRoute
  ExamensIndexRoute: typeof ExamensIndexRoute
  ExercicesIndexRoute: typeof ExercicesIndexRoute
  ExamensExamIdQuestionIdRoute: typeof ExamensExamIdQuestionIdRoute
  ExercicesChapterIdExerciseIdRoute: typeof ExercicesChapterIdExerciseIdRoute
  ExamensExamIdIndexRoute: typeof ExamensExamIdIndexRoute
  ExercicesChapterIdIndexRoute: typeof ExercicesChapterIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/': {
      id: '/exercices/'
      path: '/exercices'
      fullPath: '/exercices/'
      preLoaderRoute: typeof ExercicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examens/': {
      id: '/examens/'
      path: '/examens'
      fullPath: '/examens/'
      preLoaderRoute: typeof ExamensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstrations/': {
      id: '/demonstrations/'
      path: '/demonstrations'
      fullPath: '/demonstrations/'
      preLoaderRoute: typeof DemonstrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstrations/$demoId': {
      id: '/demonstrations/$demoId'
      path: '/demonstrations/$demoId'
      fullPath: '/demonstrations/$demoId'
      preLoaderRoute: typeof DemonstrationsDemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours/$chapterId': {
      id: '/cours/$chapterId'
      path: '/cours/$chapterId'
      fullPath: '/cours/$chapterId'
      preLoaderRoute: typeof CoursChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/$chapterId/': {
      id: '/exercices/$chapterId/'
      path: '/exercices/$chapterId'
      fullPath: '/exercices/$chapterId/'
      preLoaderRoute: typeof ExercicesChapterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examens/$examId/': {
      id: '/examens/$examId/'
      path: '/examens/$examId'
      fullPath: '/examens/$examId/'
      preLoaderRoute: typeof ExamensExamIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/$chapterId/$exerciseId': {
      id: '/exercices/$chapterId/$exerciseId'
      path: '/exercices/$chapterId/$exerciseId'
      fullPath: '/exercices/$chapterId/$exerciseId'
      preLoaderRoute: typeof ExercicesChapterIdExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examens/$examId/$questionId': {
      id: '/examens/$examId/$questionId'
      path: '/examens/$examId/$questionId'
      fullPath: '/examens/$examId/$questionId'
      preLoaderRoute: typeof ExamensExamIdQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursChapterIdRoute: CoursChapterIdRoute,
  DemonstrationsDemoIdRoute: DemonstrationsDemoIdRoute,
  DemonstrationsIndexRoute: DemonstrationsIndexRoute,
  ExamensIndexRoute: ExamensIndexRoute,
  ExercicesIndexRoute: ExercicesIndexRoute,
  ExamensExamIdQuestionIdRoute: ExamensExamIdQuestionIdRoute,
  ExercicesChapterIdExerciseIdRoute: ExercicesChapterIdExerciseIdRoute,
  ExamensExamIdIndexRoute: ExamensExamIdIndexRoute,
  ExercicesChapterIdIndexRoute: ExercicesChapterIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
