/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExercicesIndexRouteImport } from './routes/exercices.index'
import { Route as CoursChapterIdRouteImport } from './routes/cours.$chapterId'
import { Route as ExercicesChapterIdIndexRouteImport } from './routes/exercices.$chapterId.index'
import { Route as ExercicesChapterIdExerciseIdRouteImport } from './routes/exercices.$chapterId.$exerciseId'

const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesIndexRoute = ExercicesIndexRouteImport.update({
  id: '/exercices/',
  path: '/exercices/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursChapterIdRoute = CoursChapterIdRouteImport.update({
  id: '/cours/$chapterId',
  path: '/cours/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesChapterIdIndexRoute = ExercicesChapterIdIndexRouteImport.update({
  id: '/exercices/$chapterId/',
  path: '/exercices/$chapterId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesChapterIdExerciseIdRoute =
  ExercicesChapterIdExerciseIdRouteImport.update({
    id: '/exercices/$chapterId/$exerciseId',
    path: '/exercices/$chapterId/$exerciseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/planning': typeof PlanningRoute
  '/cours/$chapterId': typeof CoursChapterIdRoute
  '/exercices/': typeof ExercicesIndexRoute
  '/exercices/$chapterId/$exerciseId': typeof ExercicesChapterIdExerciseIdRoute
  '/exercices/$chapterId/': typeof ExercicesChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/planning': typeof PlanningRoute
  '/cours/$chapterId': typeof CoursChapterIdRoute
  '/exercices': typeof ExercicesIndexRoute
  '/exercices/$chapterId/$exerciseId': typeof ExercicesChapterIdExerciseIdRoute
  '/exercices/$chapterId': typeof ExercicesChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/planning': typeof PlanningRoute
  '/cours/$chapterId': typeof CoursChapterIdRoute
  '/exercices/': typeof ExercicesIndexRoute
  '/exercices/$chapterId/$exerciseId': typeof ExercicesChapterIdExerciseIdRoute
  '/exercices/$chapterId/': typeof ExercicesChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/planning'
    | '/cours/$chapterId'
    | '/exercices/'
    | '/exercices/$chapterId/$exerciseId'
    | '/exercices/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/planning'
    | '/cours/$chapterId'
    | '/exercices'
    | '/exercices/$chapterId/$exerciseId'
    | '/exercices/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/planning'
    | '/cours/$chapterId'
    | '/exercices/'
    | '/exercices/$chapterId/$exerciseId'
    | '/exercices/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanningRoute: typeof PlanningRoute
  CoursChapterIdRoute: typeof CoursChapterIdRoute
  ExercicesIndexRoute: typeof ExercicesIndexRoute
  ExercicesChapterIdExerciseIdRoute: typeof ExercicesChapterIdExerciseIdRoute
  ExercicesChapterIdIndexRoute: typeof ExercicesChapterIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/': {
      id: '/exercices/'
      path: '/exercices'
      fullPath: '/exercices/'
      preLoaderRoute: typeof ExercicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours/$chapterId': {
      id: '/cours/$chapterId'
      path: '/cours/$chapterId'
      fullPath: '/cours/$chapterId'
      preLoaderRoute: typeof CoursChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/$chapterId/': {
      id: '/exercices/$chapterId/'
      path: '/exercices/$chapterId'
      fullPath: '/exercices/$chapterId/'
      preLoaderRoute: typeof ExercicesChapterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/$chapterId/$exerciseId': {
      id: '/exercices/$chapterId/$exerciseId'
      path: '/exercices/$chapterId/$exerciseId'
      fullPath: '/exercices/$chapterId/$exerciseId'
      preLoaderRoute: typeof ExercicesChapterIdExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanningRoute: PlanningRoute,
  CoursChapterIdRoute: CoursChapterIdRoute,
  ExercicesIndexRoute: ExercicesIndexRoute,
  ExercicesChapterIdExerciseIdRoute: ExercicesChapterIdExerciseIdRoute,
  ExercicesChapterIdIndexRoute: ExercicesChapterIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
